#!/bin/sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH_NAME" = "master" ]; then
  exit 0
fi

if ! echo "$BRANCH_NAME" | grep -Eq "^SGT-[0-9]+$"; then
  echo "Nome da branch inválido. O padrão deve ser SGT-### (ex: SGT-123)."
  exit 1
fi
