#!/bin/bash
set -e

yarn prepare
yarn be:lint
# yarn fe:lint
# yarn fe:build

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH_NAME" = "master" ]; then
  exit 0
fi

if ! echo "$BRANCH_NAME" | grep -Eq "^UGE-[0-9]+$"; then
  echo "Nome da branch inválido. O padrão deve ser UGE-### (ex: UGE-123)."
  exit 1
fi
